/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Ponto;
import static Model.Quadrante.PRIMEIRO;
import static Model.Quadrante.SEGUNDO;

/**
 *
 * @author vitor-nuvme
 */
public class AppQuestao2Ui extends javax.swing.JFrame {

    /**
     * Creates new form AppGUI
     */
    public AppQuestao2Ui() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEx = new javax.swing.JLabel();
        lbEy = new javax.swing.JLabel();
        tfY = new javax.swing.JTextField();
        tfX = new javax.swing.JTextField();
        btAvaliar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ckInsideX = new javax.swing.JCheckBox();
        ckInsideY = new javax.swing.JCheckBox();
        ck1 = new javax.swing.JCheckBox();
        ck2 = new javax.swing.JCheckBox();
        ck3 = new javax.swing.JCheckBox();
        ck4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbEx.setText("Eixo X:");

        lbEy.setText("Eixo Y:");

        tfX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfXActionPerformed(evt);
            }
        });

        btAvaliar.setText("Avaliar");
        btAvaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAvaliarActionPerformed(evt);
            }
        });

        jLabel1.setText("Posição:");

        ckInsideX.setText("Inside sobre eixo X");
        ckInsideX.setEnabled(false);
        ckInsideX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckInsideXActionPerformed(evt);
            }
        });

        ckInsideY.setText("Inside sobre eixo Y");
        ckInsideY.setEnabled(false);
        ckInsideY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckInsideYActionPerformed(evt);
            }
        });

        ck1.setText("No 1º Quadrante");
        ck1.setEnabled(false);
        ck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck1ActionPerformed(evt);
            }
        });

        ck2.setText("No 2º Quadrante");
        ck2.setEnabled(false);
        ck2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck2ActionPerformed(evt);
            }
        });

        ck3.setText("No 3º Quadrante");
        ck3.setEnabled(false);
        ck3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck3ActionPerformed(evt);
            }
        });

        ck4.setText("No 4º Quadrante");
        ck4.setEnabled(false);
        ck4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ck4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEy)
                                .addGap(49, 49, 49)
                                .addComponent(tfY))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbEx)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(97, 97, 97)
                        .addComponent(btAvaliar)
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ck4)
                            .addComponent(ck3)
                            .addComponent(ck2)
                            .addComponent(ck1)
                            .addComponent(ckInsideY)
                            .addComponent(ckInsideX))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEx)
                            .addComponent(tfX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btAvaliar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEy)
                    .addComponent(tfY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(ckInsideX)
                .addGap(18, 18, 18)
                .addComponent(ckInsideY)
                .addGap(18, 18, 18)
                .addComponent(ck1)
                .addGap(18, 18, 18)
                .addComponent(ck2)
                .addGap(18, 18, 18)
                .addComponent(ck3)
                .addGap(18, 18, 18)
                .addComponent(ck4)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfXActionPerformed

    private void ckInsideXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckInsideXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckInsideXActionPerformed

    private void ckInsideYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckInsideYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckInsideYActionPerformed

    private void ck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck1ActionPerformed

    private void ck2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck2ActionPerformed

    private void btAvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAvaliarActionPerformed
        Ponto p1 = new Ponto();
        p1.setX(Integer.parseInt(tfX.getText()));
        p1.setY(Integer.parseInt(tfY.getText()));
        
        ck1.setSelected(false);
        ck2.setSelected(false);
        ck3.setSelected(false);
        ck4.setSelected(false);
        ckInsideX.setSelected(false);
        ckInsideY.setSelected(false);
        
        switch (p1.identificarQuadrante()){
       
        case PRIMEIRO:

            ck1.setSelected(true);
            break;
            
        case SEGUNDO:

            ck2.setSelected(true);
            break;  
            
        case TERCEIRO:

            ck3.setSelected(true);
            break;
            
        case QUARTO:

            ck4.setSelected(true);
            break;  
                       
        default:
            if (p1.estaIncidindoSobreX() == true){
                ckInsideX.setSelected(true);
        }
            else if(p1.estaIncidindoSobreY() == true){
                ckInsideY.setSelected(true);

            }

        }
           
                    
    }//GEN-LAST:event_btAvaliarActionPerformed

    private void ck3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck3ActionPerformed

    private void ck4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ck4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ck4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppQuestao2Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppQuestao2Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppQuestao2Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppQuestao2Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppQuestao2Ui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAvaliar;
    private javax.swing.JCheckBox ck1;
    private javax.swing.JCheckBox ck2;
    private javax.swing.JCheckBox ck3;
    private javax.swing.JCheckBox ck4;
    private javax.swing.JCheckBox ckInsideX;
    private javax.swing.JCheckBox ckInsideY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbEx;
    private javax.swing.JLabel lbEy;
    private javax.swing.JTextField tfX;
    private javax.swing.JTextField tfY;
    // End of variables declaration//GEN-END:variables
}
