/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.Estadia;
import Model.Periodo;
import javax.swing.JOptionPane;

/**
 *
 * @author Vitor da Silva
 */

public class EstadiaUI extends javax.swing.JFrame {

    /**
     * Creates new form EstadiaUI
     */
    public EstadiaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPeriodo = new javax.swing.JLabel();
        btCalcular = new javax.swing.JButton();
        tfQntDia = new javax.swing.JTextField();
        lbQntDia = new javax.swing.JLabel();
        tfPeriodo = new javax.swing.JTextField();
        lbResultado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPeriodo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbPeriodo.setText("Informe o periodo da hospedagem conforme as opções ao lado:");

        btCalcular.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btCalcular.setText("Calcular valor");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        tfQntDia.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tfQntDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQntDiaActionPerformed(evt);
            }
        });

        lbQntDia.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lbQntDia.setText("Informa a quantidade de diárias:");

        tfPeriodo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        tfPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPeriodoActionPerformed(evt);
            }
        });

        lbResultado.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("OPÇÕES DE PERIODOS PARA HOSPEDAGEM:\n* ALTA_TEMPORADA\n* MEDIA_TEMPORADA\n* BAIXA_TEMPORADA");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbQntDia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfQntDia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbPeriodo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                                .addGap(12, 12, 12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btCalcular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfQntDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQntDia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPeriodo)
                            .addComponent(tfPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCalcular))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lbResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    
    /**
     *  Botão que calcula o valor total da estadia:
     *  Pega os valores dos textFields | Valida se foi informado um periodo valido e se a quantidade de diárias não está vazia;
     *  Transforma dias para int e caso o periodo seja escrito em letras minusculas, transforma para maiusculas;
     *  Inicia o construtor com as informações/parametros;
     *  Formata a saida do calculo para ter 2 casas após a virgula;
     *  Joga o resultado em um Jlabel; 
    */ 
    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed

        String periodo = tfPeriodo.getText();
        String dias = tfQntDia.getText();
        int quantidadeDias;
        
        if (dias.equals("")){
            JOptionPane.showMessageDialog(null, "Informe um valor para quantidade de diárias", "Erro", JOptionPane.ERROR_MESSAGE);            
            throw new IllegalArgumentException ("Informe um valor para quantidade de diárias");       
        }
        else{
            quantidadeDias = Integer.parseInt(dias);
        }
                 
        if (!periodo.equalsIgnoreCase("ALTA_TEMPORADA") && !periodo.equalsIgnoreCase("MEDIA_TEMPORADA") && !periodo.equalsIgnoreCase("BAIXA_TEMPORADA")){
            JOptionPane.showMessageDialog(null, "Periodo informado inválido", "Erro", JOptionPane.ERROR_MESSAGE);            
            throw new IllegalArgumentException ("Periodo informado inválido");
        }
        else{
            periodo = periodo.toUpperCase();
            
            Estadia estadia = new Estadia(Periodo.valueOf(periodo), quantidadeDias);
            
            String valorFormat = String.format("%.2f", estadia.precoPagar());
            lbResultado.setText("O valor total da estadia é de: R$" + valorFormat);
        
        }
        
    }//GEN-LAST:event_btCalcularActionPerformed

    private void tfQntDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQntDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQntDiaActionPerformed

    private void tfPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPeriodoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadiaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadiaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadiaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadiaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadiaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbPeriodo;
    private javax.swing.JLabel lbQntDia;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JTextField tfPeriodo;
    private javax.swing.JTextField tfQntDia;
    // End of variables declaration//GEN-END:variables
}
