/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Professor;
import model.Titulacao;
import model.Turma;
import model.Turno;
/**
 *
 * @author vitor-nuvme
 */
public class TurmaUI extends javax.swing.JFrame {
    Turma turma = new Turma();
    /**
     * Creates new form TurmaUI
     */
    public TurmaUI() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rdMatutino = new javax.swing.JRadioButton();
        rdVespertino = new javax.swing.JRadioButton();
        rdNoturno = new javax.swing.JRadioButton();
        tfDisciplina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdGraduado = new javax.swing.JRadioButton();
        rdMestrado = new javax.swing.JRadioButton();
        rdDoutorado = new javax.swing.JRadioButton();
        tfNmProfessor = new javax.swing.JTextField();
        tfEmailProfessor = new javax.swing.JTextField();
        btIncluir = new javax.swing.JButton();
        btListar = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Turma");

        jLabel2.setText("Disciplina:");

        jLabel3.setText("Turno:");

        buttonGroup1.add(rdMatutino);
        rdMatutino.setText("Matutino");

        buttonGroup1.add(rdVespertino);
        rdVespertino.setText("Vespertino");
        rdVespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdVespertinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdNoturno);
        rdNoturno.setText("Noturno");

        tfDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDisciplinaActionPerformed(evt);
            }
        });

        jLabel4.setText("Professor");

        jLabel5.setText("Nome:");

        jLabel6.setText("Email:");

        jLabel7.setText("Titulação:");

        buttonGroup2.add(rdGraduado);
        rdGraduado.setText("Graduado");

        buttonGroup2.add(rdMestrado);
        rdMestrado.setText("Mestrado");

        buttonGroup2.add(rdDoutorado);
        rdDoutorado.setText("Doutorado");
        rdDoutorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDoutoradoActionPerformed(evt);
            }
        });

        tfNmProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNmProfessorActionPerformed(evt);
            }
        });

        btIncluir.setText("Incluir Aluno");
        btIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIncluirActionPerformed(evt);
            }
        });

        btListar.setText("Listar dados da turma");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(rdGraduado)
                                .addGap(46, 46, 46)
                                .addComponent(rdMestrado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btIncluir)
                                .addGap(18, 18, 18)
                                .addComponent(btListar)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDisciplina))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(rdDoutorado)
                                                    .addComponent(tfEmailProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfNmProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 3, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rdMatutino)
                                        .addGap(57, 57, 57)
                                        .addComponent(rdVespertino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rdNoturno)))))
                        .addGap(64, 64, 64))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdMatutino)
                    .addComponent(rdVespertino)
                    .addComponent(rdNoturno)
                    .addComponent(jLabel3))
                .addGap(58, 58, 58)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNmProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEmailProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rdGraduado)
                    .addComponent(rdMestrado)
                    .addComponent(rdDoutorado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIncluir)
                    .addComponent(btListar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdDoutoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDoutoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdDoutoradoActionPerformed

    private void tfNmProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNmProfessorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNmProfessorActionPerformed

    private void rdVespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdVespertinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdVespertinoActionPerformed

    private void tfDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDisciplinaActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        turma.setDisciplina(tfDisciplina.getText());
        
        if (rdMatutino.isSelected()) {
            turma.setTurno(Turno.MATUTINO);
        } 
        else if (rdVespertino.isSelected()) {
            turma.setTurno(Turno.VESPERTINO);
        } 
        else if (rdNoturno.isSelected()) {
            turma.setTurno(Turno.NOTURNO);
        } 
        
        
        if (rdGraduado.isSelected()) {
            Professor professor = new Professor(Titulacao.GRADUACAO, tfNmProfessor.getText(), tfEmailProfessor.getText());
            turma.setProfessor(professor);
        } 
        else if (rdMestrado.isSelected()) {
            Professor professor = new Professor(Titulacao.MESTRADO, tfNmProfessor.getText(), tfEmailProfessor.getText());
            turma.setProfessor(professor);
        } 
        else if (rdDoutorado.isSelected()) {
            Professor professor = new Professor(Titulacao.DOUTORADO, tfNmProfessor.getText(), tfEmailProfessor.getText());
            turma.setProfessor(professor);
        }   
        
        ListaUI consulta = new ListaUI(turma);
        consulta.setVisible(true);
    }//GEN-LAST:event_btListarActionPerformed

    private void btIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIncluirActionPerformed
        AlunoUI formularioAluno = new AlunoUI(turma);
        formularioAluno.setVisible(true);
    }//GEN-LAST:event_btIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TurmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TurmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TurmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TurmaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TurmaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIncluir;
    private javax.swing.JButton btListar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JRadioButton rdDoutorado;
    private javax.swing.JRadioButton rdGraduado;
    private javax.swing.JRadioButton rdMatutino;
    private javax.swing.JRadioButton rdMestrado;
    private javax.swing.JRadioButton rdNoturno;
    private javax.swing.JRadioButton rdVespertino;
    private javax.swing.JTextField tfDisciplina;
    private javax.swing.JTextField tfEmailProfessor;
    private javax.swing.JTextField tfNmProfessor;
    // End of variables declaration//GEN-END:variables
}
